/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Data.Connect;
import Process.NhanVien;
import Process.UpdateCombobox;
import Process.UpdateTable;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MyPC
 */
public class QLNS_NhanVien1 extends javax.swing.JFrame {
    public static Connection conn=Connect.getConnect();
    public static String idPhongban;
    public static String idChucvu;
    public static String idNhanVien;
    String sql="SELECT * FROM qlns.nhanvien";

    /**
     * Creates new form QLNS_NhanVien
     */
    public QLNS_NhanVien1() {
        initComponents();
        LoadCombobox();
        ShowBG();
    }
    public void ProcessCrt(boolean b)
    {
        this.btAdd.setEnabled(b);
        this.btDelete.setEnabled(b);
        this.btEdit.setEnabled(b);
    }
    public void ShowBG()
    {
        UpdateTable.LoadData(sql, tbNhanVien);
        this.lbTong.setText("Số bản ghi :"+this.tbNhanVien.getRowCount()+null);
    }

    public void LoadCombobox()
    {
        this.cbChucVu.removeAllItems();
        this.cbPhongban.removeAllItems();
        
        String sql="SELECT * FROM qlns.phongban";
        String sql1="SELECT * FROM qlns.chucvu";
        UpdateCombobox.LoadDataComBoBox(sql,this.cbPhongban, "name");
        UpdateCombobox.LoadDataComBoBox(sql1, cbChucVu, "name");
    }
    public String SelectedRadioBT()
    {
        String gioitinh=null;
        if(this.radioMale.isSelected())
            gioitinh=this.radioMale.getText();
        else if(this.radioFemale.isSelected())
                gioitinh=this.radioFemale.getText();
        else if(this.radioNot.isSelected())
            gioitinh=this.radioNot.getText();
        else
            JOptionPane.showMessageDialog(null, "Bạn cần nhập giới tính","Thông báo",1);
        return gioitinh;
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        cbbPhongban = new javax.swing.JPanel();
        jLabel_thongtinNV = new javax.swing.JLabel();
        jLabel_manv = new javax.swing.JLabel();
        jLabel_tennv = new javax.swing.JLabel();
        jLabel_Chucvu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_gioitinh = new javax.swing.JLabel();
        jLabel_Ngaysinh = new javax.swing.JLabel();
        jLabel_Noisinh = new javax.swing.JLabel();
        jLabel_SoCMNND = new javax.swing.JLabel();
        jLabel_Sodt = new javax.swing.JLabel();
        jLabel_Dantoc = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtdantoc = new javax.swing.JTextField();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        cbChucVu = new javax.swing.JComboBox<>();
        cbPhongban = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txttongiao = new javax.swing.JTextField();
        radioNot = new javax.swing.JRadioButton();
        txtCMND = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSerch = new javax.swing.JTextField();
        btSerch = new javax.swing.JButton();
        jPanel_Chucnang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();
        lbTong = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_thongtinNV.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_thongtinNV.setText("Thông tin nhân viên");

        jLabel_manv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_manv.setText("Mã nhân viên :");

        jLabel_tennv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_tennv.setText("Tên nhân viên:");

        jLabel_Chucvu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Chucvu.setText("Mã chức vụ  :");

        jLabel_gioitinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_gioitinh.setText("Giới tính          :");

        jLabel_Ngaysinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Ngaysinh.setText("Ngày sinh:");

        jLabel_Noisinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Noisinh.setText("Nơi sinh   :");

        jLabel_SoCMNND.setText("Số CMND :");

        jLabel_Sodt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Sodt.setText("Số điện thoại:");

        jLabel_Dantoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Dantoc.setText("Dân tộc   :");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioMale);
        radioMale.setText("Nam");
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioFemale);
        radioFemale.setText("Nữ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mã phòng ban:");

        cbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbChucVu.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbChucVuPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cbPhongban.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPhongban.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbPhongbanPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbPhongban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPhongbanActionPerformed(evt);
            }
        });

        jLabel3.setText("Tôn giáo");

        buttonGroup1.add(radioNot);
        radioNot.setText("Không xác định");
        radioNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNotActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("*");

        jLabel6.setText("*");

        jLabel7.setText("*");

        jLabel8.setText("*");

        jLabel9.setText("*");

        txtSerch.setText("Tìm Kiếm");
        txtSerch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSerchMouseClicked(evt);
            }
        });
        txtSerch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerchActionPerformed(evt);
            }
        });

        btSerch.setText("Tìm kiếm nhân viên");
        btSerch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSerchMouseClicked(evt);
            }
        });
        btSerch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSerchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cbbPhongbanLayout = new javax.swing.GroupLayout(cbbPhongban);
        cbbPhongban.setLayout(cbbPhongbanLayout);
        cbbPhongbanLayout.setHorizontalGroup(
            cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbbPhongbanLayout.createSequentialGroup()
                .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cbbPhongbanLayout.createSequentialGroup()
                        .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cbbPhongbanLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Chucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbbPhongbanLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_gioitinh)))
                        .addGap(18, 18, 18)
                        .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioNot)
                            .addGroup(cbbPhongbanLayout.createSequentialGroup()
                                .addComponent(radioFemale)
                                .addGap(18, 18, 18)
                                .addComponent(radioMale))))
                    .addGroup(cbbPhongbanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(cbbPhongbanLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbPhongban, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(cbbPhongbanLayout.createSequentialGroup()
                                .addComponent(jLabel_manv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaNV))
                            .addComponent(jLabel_thongtinNV)
                            .addGroup(cbbPhongbanLayout.createSequentialGroup()
                                .addComponent(jLabel_tennv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cbbPhongbanLayout.createSequentialGroup()
                                        .addComponent(cbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)))))))
                .addGap(21, 21, Short.MAX_VALUE)
                .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cbbPhongbanLayout.createSequentialGroup()
                        .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cbbPhongbanLayout.createSequentialGroup()
                                .addComponent(jLabel_SoCMNND)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cbbPhongbanLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cbbPhongbanLayout.createSequentialGroup()
                                .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Ngaysinh)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(cbbPhongbanLayout.createSequentialGroup()
                        .addComponent(jLabel_Noisinh)
                        .addGap(18, 18, 18)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cbbPhongbanLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Dantoc)
                            .addComponent(jLabel_Sodt))
                        .addGap(31, 31, 31)
                        .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttongiao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtdantoc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtphone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                    .addGroup(cbbPhongbanLayout.createSequentialGroup()
                        .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btSerch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(128, 128, 128))
        );
        cbbPhongbanLayout.setVerticalGroup(
            cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbbPhongbanLayout.createSequentialGroup()
                .addComponent(jLabel_thongtinNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_manv)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel_Sodt)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cbbPhongbanLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Ngaysinh)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Dantoc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdantoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(6, 6, 6)
                        .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Chucvu)
                            .addComponent(cbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(cbbPhongbanLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)))
                .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cbbPhongbanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cbbPhongbanLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(cbbPhongbanLayout.createSequentialGroup()
                                .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbPhongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioNot)
                                    .addComponent(jLabel_Noisinh)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioFemale)
                                    .addComponent(radioMale))
                                .addContainerGap())))
                    .addGroup(cbbPhongbanLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_SoCMNND, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttongiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cbbPhongbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSerch)
                            .addComponent(btSerch, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
        );

        jPanel_Chucnang.setBackground(new java.awt.Color(238, 220, 130));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Chức năng");

        btBack.setBackground(new java.awt.Color(51, 255, 255));
        btBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBack.setText("Quay Lại");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btAdd.setBackground(new java.awt.Color(255, 204, 0));
        btAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAdd.setText("Thêm");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btEdit.setBackground(new java.awt.Color(255, 255, 0));
        btEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEdit.setText("Sửa");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDelete.setBackground(new java.awt.Color(255, 255, 51));
        btDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDelete.setText("Xóa");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ChucnangLayout = new javax.swing.GroupLayout(jPanel_Chucnang);
        jPanel_Chucnang.setLayout(jPanel_ChucnangLayout);
        jPanel_ChucnangLayout.setHorizontalGroup(
            jPanel_ChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChucnangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_ChucnangLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btBack)
                .addGap(111, 111, 111)
                .addComponent(btAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 434, Short.MAX_VALUE)
                .addComponent(btEdit)
                .addGap(69, 69, 69)
                .addComponent(btDelete)
                .addGap(25, 25, 25))
        );
        jPanel_ChucnangLayout.setVerticalGroup(
            jPanel_ChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChucnangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBack)
                    .addComponent(btAdd)
                    .addComponent(btEdit)
                    .addComponent(btDelete))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 211, 155));

        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        tbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhanVien);

        lbTong.setText("jLabel5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbTong, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTong))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Chucnang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbPhongban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbPhongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Chucnang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed

        if(this.txtMaNV.getText().length()==0)
            JOptionPane.showMessageDialog(null, "Bạn cần nhập Mã Nhân viên","Thông báo",1);
        else if(this.txtMaNV.getText().length()>10)
            JOptionPane.showMessageDialog(null, "Số kí tự mã nhân viên không vượt quá 10","Thông báo",1);
        else if(this.txtName.getText().length()==0 || this.txtDate.getText().length()==0)
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ dữ liệu. Trường có dấu * bên cạnh là bắt buộc","Thông báo",1);
        else
        {
            String gioitinh=SelectedRadioBT();
            try {
                //            System.out.println(this.txtMaNV.getText().trim());
//            System.out.println(this.txtName.getText().trim());
//            System.out.println(gioitinh);
//            System.out.println(this.txtCMND.getText().trim());
//            System.out.println(this.txtDate.getText().trim());
//            System.out.println(this.txtAddress.getText().trim());
//            System.out.println(this.txtphone.getText().trim());
//            System.out.println(this.txtdantoc.getText().trim());
//            System.out.println(this.txttongiao.getText().trim());
NhanVien.InsertNhanVien(this.txtMaNV.getText().trim(), this.txtName.getText(), gioitinh, this.txtCMND.getText()
        , this.txtDate.getText(), this.txtAddress.getText(), this.txtphone.getText(),
        this.txtdantoc.getText(), this.txttongiao.getText(), idPhongban, idChucvu);
            } catch (ParseException ex) {
                Logger.getLogger(QLNS_NhanVien1.class.getName()).log(Level.SEVERE, null, ex);
            }
            ShowBG();
            ProcessCrt(false);
            
           
        }
            
    }//GEN-LAST:event_btAddActionPerformed

    private void cbPhongbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPhongbanActionPerformed
       
    }//GEN-LAST:event_cbPhongbanActionPerformed

    private void cbPhongbanPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbPhongbanPopupMenuWillBecomeInvisible
       String sql="SELECT * FROM qlns.phongban where name=?";
       try
       {
           PreparedStatement pst= conn.prepareStatement(sql);
           pst.setString(1 , (String)this.cbPhongban.getSelectedItem());
           ResultSet rs = pst.executeQuery();
           while(rs.next())
           {
               //co tu ten roi thy bay gio minh se luu tam duoc cai id cua no ra de sau nay minh lay so sanh voi id 
               idPhongban =rs.getString("idPhongban");
               
           } 
           System.out.println("IdPhongban : "+idPhongban);
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, "Thông báo lỗi");
       }
    }//GEN-LAST:event_cbPhongbanPopupMenuWillBecomeInvisible

    private void cbChucVuPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbChucVuPopupMenuWillBecomeInvisible
        String sql="SELECT * FROM qlns.chucvu where name=?";
       try
       {
           PreparedStatement pst= conn.prepareStatement(sql);
           pst.setString(1 , (String)this.cbChucVu.getSelectedItem());
           ResultSet rs = pst.executeQuery();
           while(rs.next())
           {
               //co tu ten roi thy bay gio minh se luu tam duoc cai id cua no ra de sau nay minh lay so sanh voi id 
               idChucvu =rs.getString("idChucVu");
               
           } 
           System.out.println("IdChucVu : "+idChucvu);
       }catch(Exception e)
       {
           
       }
    }//GEN-LAST:event_cbChucVuPopupMenuWillBecomeInvisible

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMaleActionPerformed

    private void radioNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNotActionPerformed
       
    }//GEN-LAST:event_radioNotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.txtMaNV.setText(null);
      this.txtName.setText(null);
      this.txtCMND.setText(null);
      this.txtAddress.setText(null);
      this.txtDate.setText(null);
      this.txtdantoc.setText(null);
      this.txtphone.setText(null);
      this.txttongiao.setText(null);
      ShowBG();
        ProcessCrt(false);
      this.btAdd.setEnabled(true);
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void tbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanVienMouseClicked
        ProcessCrt(true);
        this.btAdd.setEnabled(false);
        
        try
        {
            // lấy ra dòng dữ liệu vừa clcik chuột và trỏ nó đến id của nó 
            int row=this.tbNhanVien.getSelectedRow();
            String IDRow=(this.tbNhanVien.getModel().getValueAt(row, 0)).toString();
            String sql1="SELECT * FROM qlns.nhanvien where idNhanvien='"+IDRow+"'";
            // đọc dữ liệu có mã là idRow rồi ghi nó lên cách textfield và combobox
            ResultSet rs = UpdateTable.ShowData(sql1);
            if(rs.next())// nêys có dữ liệu
            {
                idNhanVien=rs.getString("idNhanVien");
                this.txtMaNV.setText(rs.getString("idNhanVien"));
                this.txtName.setText(rs.getString("name"));
                this.txtAddress.setText(rs.getString("Address"));
                this.txtphone.setText(rs.getString("phone"));
                this.txtCMND.setText(rs.getString("CMND"));
                this.txtDate.setText(rs.getString("Birthday"));
                this.txtdantoc.setText(rs.getString("dantoc"));
                this.txttongiao.setText(rs.getString("tongiao"));
                String s = rs.getString("sex");
                if((this.radioMale.getText()).equalsIgnoreCase(s))
                {
                     this.radioMale.setSelected(true);
                }
                   
                else
                    if((this.radioFemale.getText()).equalsIgnoreCase(s))
                    {
                        this.radioFemale.setSelected(true);
                    }
                   
                else if((this.radioNot.getText()).equalsIgnoreCase(s))
                {
                     this.radioNot.setSelected(true);
                }
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Thông báo lỗi");
            
        }
    }//GEN-LAST:event_tbNhanVienMouseClicked

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        QLNS_Menu menu = new QLNS_Menu();
        this.dispose();
        menu.setVisible(true);
        
    }//GEN-LAST:event_btBackActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed

        if(this.txtMaNV.getText().length()==0)
            JOptionPane.showMessageDialog(null, "Mã nhân viên không được để trống","Thông báo",1);
        else
            if(this.txtMaNV.getText().length() >10)
                JOptionPane.showMessageDialog(null, "Mã nhân viên không được quá 10 kí tự","Thông báo",1);
        else
            {
                String gioitinh = SelectedRadioBT();
                
            try {
                NhanVien.UpdateNhanVien(this.txtMaNV.getText().trim(), this.txtName.getText(), gioitinh, this.txtCMND.getText(), 
                        this.txtDate.getText(), this.txtAddress.getText(), this.txtphone.getText(), this.txtdantoc.getText(),
                        this.txttongiao.getText(),idPhongban, idChucvu, idNhanVien);
            } catch (ParseException ex) {
                Logger.getLogger(QLNS_NhanVien1.class.getName()).log(Level.SEVERE, null, ex);
            }
                ShowBG();
                ProcessCrt(false);
            }
        
    }//GEN-LAST:event_btEditActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
       
        if(this.txtMaNV.getText().length()==0)
           JOptionPane.showMessageDialog(null, "Không tìm thấy Mã nhân viên nào cần xóa","Thông Báo",1);
       else
       {
           if(JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa ?","Thông báo",2)==0)
           {
               NhanVien.DeleteNhanVien(idNhanVien);
               ShowBG();
               ProcessCrt(false);
           }
       }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void txtSerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerchActionPerformed

        
        
    }//GEN-LAST:event_txtSerchActionPerformed

    private void txtSerchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSerchMouseClicked
       this.txtSerch.setText(null);
       this.txtSerch.requestFocus();
       ShowBG();
    }//GEN-LAST:event_txtSerchMouseClicked

    private void btSerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSerchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSerchActionPerformed

    private void btSerchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSerchMouseClicked
       if(this.txtSerch.getText().length()==0)
           JOptionPane.showMessageDialog(null, "Bạn chưa nhập từ khóa để tìm kiếm","Thông báo",1);
       else
       {
           String sql="SELECT *FROM qlns.nhanvien WHERE idNhanvien like'%"+this.txtSerch.getText()+"%' or name like'%"+this.txtSerch.getText()+"%' or Address like'%"+this.txtSerch.getText()+"%'or sex like'%"+this.txtSerch.getText()+"%' or cmnd like'%"+this.txtSerch.getText()+"%' or birthday like'%"+this.txtSerch.getText()+"%' or dantoc like'%"+this.txtSerch.getText()+"%' or tongiao like'%"+this.txtSerch.getText()+"%'or Phongban_id like'%"+this.txtSerch.getText()+"%'or Chucvu_id like'%"+this.txtSerch.getText()+"%'";
           UpdateTable.LoadData(sql, tbNhanVien);
           this.lbTong.setText("Số bản ghi :"+tbNhanVien.getRowCount());
       }
    }//GEN-LAST:event_btSerchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNS_NhanVien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNS_NhanVien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNS_NhanVien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNS_NhanVien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNS_NhanVien1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btSerch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbChucVu;
    private javax.swing.JComboBox<String> cbPhongban;
    private javax.swing.JPanel cbbPhongban;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Chucvu;
    private javax.swing.JLabel jLabel_Dantoc;
    private javax.swing.JLabel jLabel_Ngaysinh;
    private javax.swing.JLabel jLabel_Noisinh;
    private javax.swing.JLabel jLabel_SoCMNND;
    private javax.swing.JLabel jLabel_Sodt;
    private javax.swing.JLabel jLabel_gioitinh;
    private javax.swing.JLabel jLabel_manv;
    private javax.swing.JLabel jLabel_tennv;
    private javax.swing.JLabel jLabel_thongtinNV;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Chucnang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbTong;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JRadioButton radioNot;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSerch;
    private javax.swing.JTextField txtdantoc;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txttongiao;
    // End of variables declaration//GEN-END:variables
}
